seed: 0
dataset: Fluo-C2DL-Huh7
model: SA2Net2D
device: cuda
id: lr1e-4_mse1_perc0_dice1000_channels32_wbce-positive-frac0.5_wbce-weight-power3
checkpoint_freq: 100
model_arguments:
  n_channels: 1
  base_channel: 32
  n_classes: 2
  img_size: 512
optimizer_arguments:
  epochs: 200
  lr: 0.0001
  valid_freq: 1
  wbce_weight: 1
  dice_weight: 1000
  perc_weight: 0
  weight_power: 3
  wbce_positive_frac: 0.5
dataset_arguments:
  device: cpu
  im_size: 512
  load_limit: ~
dataloader_arguments:
  batch_size: 4
