seed: 0
dataset: Fluo-N2DH-SIM+
model: MARM_UNet2D
device: cuda
id: lr1e-4_mse1_perc0_dice100_channels32_wbce-positive-frac0.15_wbce-weight-power5
checkpoint_freq: 100
model_arguments:
  channels: 32
  img_channels: 1
optimizer_arguments:
  epochs: 500
  lr: 0.0001
  valid_freq: 1
  wbce_weight: 1
  dice_weight: 100
  perc_weight: 0
  weight_power: 5
  wbce_positive_frac: 0.15
dataset_arguments:
  device: cpu
  im_size: 512
  load_limit: ~
dataloader_arguments:
  batch_size: 4
