seed: 0
dataset: STARE
model: BiMAR_UDet2D
device: cuda
id: lr1e-4_wbce0.999_div1_channels32_wbce-positive-frac0.5_wbce-weight-power5
checkpoint_freq: 100
model_arguments:
  channels: 32
  img_channels: 3
optimizer_arguments:
  epochs: 300
  lr: 0.0001
  valid_freq: 1
  wbce_weight: 0.999
  perc_weight: 0
  div_weight: 1
  weight_power: 5
  wbce_positive_frac: 0.5
dataset_arguments:
  device: cpu
  tile_size: 96
  load_limit: ~
dataloader_arguments:
  batch_size: 128
