seed: 0
dataset: Fluo-N2DH-GOWT1
model: BiSE_MARM_UDet2D
device: cuda
id: lr1e-4_wbce0.5_div1_channels32_wbce-positive-frac0.25_wbce-weight-power5
checkpoint_freq: 100
model_arguments:
  channels: 32
  img_channels: 3
optimizer_arguments:
  epochs: 50
  lr: 0.0001
  valid_freq: 1
  wbce_weight: 0.5
  perc_weight: 0
  div_weight: 1
  weight_power: 5
  wbce_positive_frac: 0.25
dataset_arguments:
  device: cpu
  im_size: 512
  tile_size: 96
  load_limit: ~
dataloader_arguments:
  batch_size: 128
