seed: 0
dataset: BF-C2DL-HSC
model: UNet2D
device: cuda
id: test
checkpoint_freq: 100
model_arguments:
  channels: 16
  img_channels: 1
optimizer_arguments:
  epochs: 10
  lr: 0.0001
  valid_freq: 1
  wbce_weight: 1
  dice_weight: 100
  perc_weight: 1
  weight_power: 5
  wbce_positive_frac: 0.15
dataset_arguments:
  device: cpu
  im_size: 256
  load_limit: 16
dataloader_arguments:
  batch_size: 8
